import { expect, test } from "@playwright/test"
import { startHarness, type Harness } from "./fixture"
import { turns, webToken } from "./driver"

let harness: Harness
test.beforeAll(async () => { harness = await startHarness() })
test.afterAll(async () => { await harness.stop() })

test("semantic zoom keeps roots mounted and pins selection", async ({ browser }) => {
  const session = await harness.openSession(browser, "alice")
  const page = session.page
  const card = page.locator(".og-card").first()
  const id = await card.getAttribute("data-id")
  await page.evaluate((nodeId) => {
    ;(window as any).__ui4Root = document.querySelector(`.og-card[data-id="${nodeId}"]`)
  }, id)
  await page.evaluate((nodeId) => (window as any).__og_e2e.focusNode(nodeId, 1.5), id)
  await expect(page.locator(".canvas-wrap")).toHaveAttribute("data-lod", "node")
  await expect(card.locator(".og-markdown")).toBeVisible()
  await page.evaluate((nodeId) => (window as any).__og_e2e.focusNode(nodeId, 0.8), id)
  await expect(page.locator(".canvas-wrap")).toHaveAttribute("data-lod", "floor")
  await expect(card.locator(".og-markdown")).toBeHidden()
  await expect(card.locator(".og-card-status")).toBeVisible()
  await card.click()
  await expect(card).toHaveAttribute("data-pinned", "true")
  await expect(page.locator("#modal")).toHaveCount(0)
  await page.evaluate((nodeId) => (window as any).__og_e2e.focusNode(nodeId, 0.2), id)
  await expect(page.locator(".canvas-wrap")).toHaveAttribute("data-lod", "tower")
  await expect(page.locator(`.og-card[data-id="${id}"] .og-markdown`)).toBeVisible()
  await expect(page.locator('.og-card[data-pinned="false"] .og-dot').first()).toBeVisible()
  expect(await page.evaluate((nodeId) => (window as any).__ui4Root === document.querySelector(`.og-card[data-id="${nodeId}"]`), id)).toBe(true)
  await page.locator("#panel .close").click()
  await expect(page.locator(`.og-card[data-id="${id}"]`)).toHaveAttribute("data-pinned", "false")
  await expect(page.locator(`.og-card[data-id="${id}"]`)).toHaveCSS("width", "14px")
  await expect(page.locator(".react-flow__minimap")).toBeVisible()
  await expect(page.locator("#state-legend")).toBeVisible()

  await page.evaluate(([nodeId]) => (window as any).__og_e2e.setNodeResponsibility(nodeId, "# ADR seguro\n\n- item\n\n| A | B |\n| - | - |\n| 1 | 2 |\n\n<script>alert(1)</script><iframe src='x'></iframe>"), [id])
  await page.evaluate((nodeId) => (window as any).__og_e2e.focusNode(nodeId, 1.5), id)
  const rich = page.locator(`.og-card[data-id="${id}"] .og-markdown`)
  await expect(rich.locator("h1")).toHaveText("ADR seguro")
  await expect(rich.locator("li")).toHaveText("item")
  await expect(rich.locator("table")).toBeVisible()
  await expect(rich.locator("script, iframe")).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)

  const freeHeader = page.locator(".og-cell-header").first()
  const targetCell = await freeHeader.getAttribute("data-cell")
  const bob = await harness.openSession(browser, "bob")
  await bob.page.evaluate((cell) => (window as any).__og_e2e.setFocus(cell), targetCell)
  const bobToken = await webToken(bob.page)
  const opened = await turns(harness, bobToken).open([targetCell!], "UI-4 collaboration evidence")
  expect(opened.ok).toBe(true)
  expect((await turns(harness, bobToken).claim(opened.csId, { kind: "claim.add", payload: { id: "ui4-draft", subject: "draft", domain: targetCell!.split(":")[0], level: targetCell!.split(":")[1], refs: [] } })).ok).toBe(true)
  await expect(freeHeader.locator(".og-lock-badge")).toContainText("bob")
  await expect(freeHeader.locator(".og-cell-avatars")).toContainText("B")
  await page.evaluate((nodeId) => (window as any).__og_e2e.focusNode(nodeId, 0.8), id)
  await expect(page.locator(`.og-card[data-id="${id}"] .og-card-status`)).toBeVisible()
  await expect(page.locator(`.og-card[data-id="${id}"] .og-card-avatars`)).toContainText("B")
  await page.evaluate((nodeId) => (window as any).__og_e2e.focusNode(nodeId, 1.5), id)
  await expect(page.locator(`.og-cell-container[data-cell="${targetCell}"] .og-ghost-card`)).toContainText("Rascunho")
  expect((await freeHeader.locator(".og-lock-badge").getAttribute("aria-label"))!).not.toContain("u_")
  await turns(harness, bobToken).abort(opened.csId)
  await page.evaluate(() => (window as any).__og_e2e.setFocus("auth:P5"))
  const emptyLock = await turns(harness, bobToken).open(["auth:P5"], "empty cell lock evidence")
  expect(emptyLock.ok).toBe(true)
  await expect(page.locator('#empty-cell-locks [data-cell="auth:P5"]')).toContainText("bob")
  await turns(harness, bobToken).abort(emptyLock.csId)
  await bob.context.close()
  await expect(freeHeader.locator(".og-lock-badge")).toHaveCount(0)

  await page.evaluate(([nodeId, cell]) => {
    ;(window as any).__og_e2e.setNodeDrift(nodeId, "critical")
    ;(window as any).__og_e2e.setCellAuthority(cell, "suspended")
  }, [id, targetCell])
  await expect(page.locator(`.og-card[data-id="${id}"] .og-node-status`)).toContainText("suspended")
  await expect(page.locator(`.og-card[data-id="${id}"] .og-node-status`)).toContainText("drift")

  await freeHeader.click()
  await expect(page.locator("#modal")).toBeVisible()
  await expect(page.locator("#modal .cd")).toHaveValue(targetCell!.split(":")[0]!)
  await expect(page.locator("#modal .cl")).toHaveValue(targetCell!.split(":")[1]!)
  await page.locator("#modal button", { hasText: "Cancelar" }).click().catch(() => page.locator("#modal button", { hasText: "Fechar" }).click())

  const viewportBefore = await page.evaluate(() => (window as any).__og_e2e.getViewport())
  await page.locator(".react-flow__minimap").click({ position: { x: 12, y: 12 } })
  await expect.poll(async () => JSON.stringify(await page.evaluate(() => (window as any).__og_e2e.getViewport()))).not.toBe(JSON.stringify(viewportBefore))
  await session.context.close()
})
